name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Install kubectl manually instead of using azure/setup-kubectl
    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    # Set up kubeconfig for MicroK8s
    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${KUBECONFIG_CONTENTS}" > ~/.kube/config

    # Deploy Kubernetes manifests
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/

